### ISSUE TITLE
Unable to build with sbt-0.13

### ISSUE THREAD

**Issue by carymrobbins** [steppenwells/sbt-sh#5]
When compiling it seems that `sbt.CommandSupport` cannot be found.

```
 sbt-sh git:(master) sbt      
[info] Loading global plugins from /home/crobbins/.sbt/0.13/plugins
[info] Set current project to xsbt-sh (in build file:/home/crobbins/build/sbt-sh/)
> ; clean ; cleanFiles ; compile
[success] Total time: 0 s, completed Apr 7, 2015 9:43:18 AM
[info] List(/home/crobbins/build/sbt-sh/lib_managed, /home/crobbins/build/sbt-sh/target)
[info] Updating {file:/home/crobbins/build/sbt-sh/}sbt-sh...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /home/crobbins/build/sbt-sh/target/scala-2.10/sbt-0.13/classes...
[error] /home/crobbins/build/sbt-sh/src/main/scala/org/sbtsh/SbtShPlugin.scala:4: object CommandSupport is not a member of package sbt
[error] import sbt.CommandSupport._
[error]            ^
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 3 s, completed Apr 7, 2015 9:43:21 AM
```
