### PR TITLE
Adjust to sbt 0.13

### PR DESCRIPTION
**Pull request by eed3si9n**
### steps
1. try using sbt-sh with sbt 0.13
### problem

```
[error] /Users/xxx/.sbt/0.13.0/staging/1234/sbt-sh/src/main/scala/org/sbtsh/SbtShPlugin.scala:4: object CommandSupport is not a member of package sbt
[error] import sbt.CommandSupport._
[error]            ^
[error] one error found
[error] ({git://github.com/steppenwells/sbt-sh.git}sbt-sh/compile:compile) Compilation failed
```
### what this changes

It removes the import line.

### CODE REVIEW

**Comment by hanxue** [comment]
Thank you very much for the step-by-step explanation, Eugene! And thanks for making sbt-sh work on `sbt 0.13.x` too.
